window.$ = require('libs/jquery.min');
window._ = require('libs/underscore');
window.Backbone = require('libs/backbone');
window.appView = $('#container');
require('libs/router');
require('libs/jquery.cookie');
window.urls = require('libs/urls');
require('libs/dialog');
window.utils = require('libs/utils');
utils.initPage();
